/**----------------------------------------------------------------------------
Copyright (c) 2015-, UT-Battelle LLC
All rights reserved.

Authors: Jay Jay Billings, Phil Evans, Alex McCaskey
Author Contact: Phil Evans, evanspg@ornl.gov

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of kettransclient nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-----------------------------------------------------------------------------*/
#ifndef TESTERPROPERTYTYPE_H
#define TESTERPROPERTYTYPE_H

/**
 * The TesterPropertyType enumeration consists of literals representing each type of configuration property
 * used by UpdaterTester and LibcurlUtilsTester.
 */
enum TesterPropertyType {

    /**
     * This literal indicates the maximum number of posts that are randomly selected by the tester.
     */
    MAX_NUMBER_OF_POSTS = 0,

    /**
     * This literal indicates the maximum amount of time in milliseconds between each random post.
     */
    MAX_POST_TIME_INTERVAL,

    /**
     * This literal indicates the url to the directory containing the required remote host testing files.
     */
    URL_PATH,

    /**
     * This literal indicates whether or not cURL calls will verify that the server's certificate
     * was generated by a Certificate Authority.
     */
    IGNORE_SSL_PEER_VERIFICATION,

    /**
     * The user name for the test
     */
    USER_NAME,

    /**
     * The password for the test
     */
    PASS_WORD

};

#endif
